// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitorsApp.DAOSQL;

#nullable disable

namespace MonitorsApp.DAOSQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240125013805_UpdateDatabase")]
    partial class UpdateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("MonitorsApp.DAOSQL.EfCoreMonitor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Matrix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProducerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RefreshRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ProducerID");

                    b.ToTable("Monitors");
                });

            modelBuilder.Entity("MonitorsApp.DAOSQL.EfCoreProducer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("MonitorsApp.DAOSQL.EfCoreMonitor", b =>
                {
                    b.HasOne("MonitorsApp.DAOSQL.EfCoreProducer", "Producer")
                        .WithMany("Monitors")
                        .HasForeignKey("ProducerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("MonitorsApp.DAOSQL.EfCoreProducer", b =>
                {
                    b.Navigation("Monitors");
                });
#pragma warning restore 612, 618
        }
    }
}
